[package]
name = "alive_in_lean"
version = "0.1"
lean_version = "3.4.2"

[dependencies]
smt2_interface = {git = "https://github.com/leanprover/smt2_interface.git", rev = "985cf270aee985e632d78b12f82bca3ac35165f5"}
mathlib = {git = "https://github.com/leanprover/mathlib.git", rev = "019b2364cadb1dd8b30c9f13c602d61c19d3b6ea"}
